
local alien_boss_lvl_id = 75
local astroid_lvl_id = 197
local bat_cave_lvl_id = 263
local cave_maze_lvl_id = 88
local clothes_drying_lvl_id = 340
local find_slippers_lvl_id = 476
local fishing_lvl_id = 389
local fishman_tex_id = 529
local help_pinky_lvl_id = 318
local interview_hero_village_lvl_id = 331
local jewel_cave_lvl_id = 447
local lottery_lvl_id = 19
local memory_lvl_id = 223
local mouse_cave_lvl_id = 520
local music_game_lvl_id = 458
local pair_game_lvl_id = 107
local pick_trash_lvl_id = 111
local puzzle_lvl_id = 221
local racing_lvl_id = 330
local rainbow_lvl_id = 234
local red_training_lvl_id = 557
local seek_frog_lvl_id = 24
local set_clock_lvl_id = 478
local snake_cave_lvl_id = 392
local shadow_lvl_id = 22
local slap_mouse_lvl_id = 54
local white_training_lvl_id = 564

local bebe_tex_id = 215
local brother1_tex_id = 280
local brother2_tex_id = 281
local castle_obj_id = 454
local cave_door_tex_id = 0
local chest_tex_id = 13
local computer_tex_id = 394
local dock_tex_id = 336
local dog_tex_id = 2
local dwarf_tex_id = 87
local elder_glass_tex_id = 108
local elder_white_tex_id = 110
local elder_yellow_tex_id = 106
local flashlight_tex_id = 380
local frog_tex_id = 357
local grandpa_tex_id = 327
local kai_tex_id = 49
local laalaa_tex_id = 211
local magic_mama_tex_id = 11
local merchant_tex_id = 305
local mirror_tex_id = 184
local my_guan_tex_id = 468
local my_mama_tex_id = 469
local my_ming_tex_id = 470
local my_papa_tex_id = 471
local old_lady_tex_id = 115
local pinky_papa_tex_id = 20
local pinky_tex_id = 316
local pinnote_tex_id = 314
local po_tex_id = 212
local priest_tex_id = 304
local red_castle_obj_id = 548
local teacher_tex_id = 276
local tinkywinky_tex_id = 214
local ufo_obj_id = 343
local well_tex_id = 181
local white_castle_obj_id = 549
local zhang_mama_tex_id = 329

local color_olive = 0xff808000

TalkData = {
  -- Teacher.
  [1] = {
    {FadeTo = {ONE_SECOND_TICK, COLOR_BLACK}},
    {Text = '唧唧啾啾'},
    {Text = '小鳥在講話'},
    {Text = '唧唧啾啾'},
    {FadeTo = {ONE_SECOND_TICK, color_olive}},
    {Text = '「哦哦天亮了去找師父吧」'},
    {Image = teacher_tex_id},
    {Text = '小秋徒兒你來啦'},
    {Text = '勇者山上的修行告一段落'},
    {Text = '你可以下山磨練磨練了'},
    {Text = '作完功課後再來見我吧'},
    {LevelId = TRAINING_MAP_LVL_ID},
  },
  [2] = {
    {ScriptNextId = ScriptHeroMtNextId},
  },
  [50] = {
    {Image = teacher_tex_id},
    {Text = '小秋徒兒你作完功課了啊'},
    {Image = BOU_TEX_ID},
    {Text = '這個缽你帶下山吧'},
    {Script = ScriptAddBou1},
    {Text = '下山後好好修行'},
    {Image = teacher_tex_id},
    {Text = '要常回來勇者山看看哪'},
    {LevelId = MAIN_MAP_LVL_ID},
  },
  [51] = {
    {Image = teacher_tex_id},
    {Text = '勇猛精進！'},
    {LevelId = MAIN_MAP_LVL_ID},
  },
  [52] = {
    {Image = teacher_tex_id},
    {Text = '小秋徒兒你回來的正好'},
    {Image = LETTER_TEX_ID},
    {Text = '山下教堂的吳神父是我的老朋友'},
    {Text = '替我將這封信交給他吧'},
    {Script = ScriptSendTeacherLetter},
    {LevelId = MAIN_MAP_LVL_ID},
  },
  [53] = {
    {Image = teacher_tex_id},
    {Text = '小秋徒兒你回來了啊'},
    {Text = '跟師兄們作作功課忘掉世間雜染'},
    {LevelId = TRAINING_MAP_LVL_ID},
  },
  -- Brother 1.
  [100] = {
    {Image = brother1_tex_id},
    {Text = '大師兄和你一起認真作功課'},
    {Text = '下山後可要好好的修行'},
    {LevelId = TRANINING_CLICK_LVL_ID},
  },
  [150] = {
    {Image = brother1_tex_id},
    {Text = '自強不息'},
    {LevelId = TRAINING_MAP_LVL_ID},
  },
  [180] = {
    {Image = brother1_tex_id},
    {Text = '遇到困難了嗎？'},
    {LevelId = MAIN_MAP_LVL_ID},
  },
  -- Brother 2.
  [200] = {
    {Image = brother2_tex_id},
    {Text = '二師兄真替你開心'},
    {Text = '撿完材火後就可以下山去修練了'},
    {Text = '別太貪玩哪'},
    {LevelId = TRANINING_STICK_LVL_ID},
  },
  [250] = {
    {Image = brother2_tex_id},
    {Text = '終於作完啦'},
    {LevelId = TRAINING_MAP_LVL_ID},
  },
  [280] = {
    {Image = brother2_tex_id},
    {Text = '怎麼這麼快就回來啦'},
    {LevelId = MAIN_MAP_LVL_ID},
  },
  -- Main map merchant.
  [300] = {
    {Image = merchant_tex_id},
    {Text = '小師父這裡有個好東西讓你看看'},
    {Image = BOU2_TEX_ID},
    {Text = '這個缽很棒吧'},
    {Text = string.format('有緣價算你%d塊錢', BOU2_COST)},
    {Script = ScriptBuyBou2},
    {Image = merchant_tex_id},
    {Text = '銘謝惠顧'},
    {LevelId = MAIN_MAP_LVL_ID},
  },
  [400] = {
    {Image = merchant_tex_id},
    {Text = '小師父好久不見'},
    {Text = '生意愈作愈大啦'},
    {Text = '今日向您推薦個絕世好缽'},
    {Image = BOU3_TEX_ID},
    {Text = '怎麼樣這個缽是不是很棒啊'},
    {Text = string.format('今日特價算你%d塊錢', BOU3_COST)},
    {Script = ScriptBuyBou3},
    {Image = merchant_tex_id},
    {Text = '銘謝惠顧'},
    {LevelId = MAIN_MAP_LVL_ID},
  },
  [450] = {
    {NextCond = RandCond, NextId = 500},
    {Image = pinnote_tex_id},
    {Text = '補貨中下次再來'},
    {LevelId = MAIN_MAP_LVL_ID},
  },
  [500] = {
    {Image = pinnote_tex_id},
    {Text = '今日公休'},
    {LevelId = MAIN_MAP_LVL_ID},
  },
  [510] = {
    {Image = merchant_tex_id},
    {Text = '小師父恭喜發財啊'},
    {Text = '今天有個好消息讓你知道'},
    {Text = '賽魂世界隆重開幕啦'},
    {Text = '只要下注猜中了包你贏大錢'},
    {Text = '有錢沒錢都來看看吧'},
    {LevelId = racing_lvl_id},
  },
  [511] = {
    {Image = merchant_tex_id},
    {Text = '歡迎來到賽魂世界'},
    {LevelId = racing_lvl_id},
  },
  [512] = {
    {Image = merchant_tex_id},
    {Text = '小師父恭喜發財啊'},
    {Text = '昨晚我家的龍神太子托夢給我'},
    {Text = '說祂發了大願讓我找到您'},
    {Text = '要蓋間廟讓善男信女們都發大財'},
    {Image = GODZILLA_TEX_ID},
    {Script = ScriptGiveGodzilla},
    {Text = '恭請金尊到鎮上募款蓋廟吧'},
    {LevelId = MAIN_MAP_LVL_ID},
  },
  -- Bag.
  [600] = {
    {Image = BOU_TEX_ID},
    {Text = '有點老舊的木缽'},
    {LevelId = BAG_LVL_ID},
  },
  [601] = {
    {Image = BOU2_TEX_ID},
    {Text = '銅製作的缽'},
    {LevelId = BAG_LVL_ID},
  },
  [602] = {
    {Image = BOU3_TEX_ID},
    {Text = '金光閃閃的缽'},
    {LevelId = BAG_LVL_ID},
  },
  [603] = {
    {Image = LETTER_TEX_ID},
    {Text = '師父給吳神父的書信'},
    {LevelId = BAG_LVL_ID},
  },
  [604] = {
    {Image = GODZILLA_TEX_ID},
    {Text = '龍神太子神像'},
    {LevelId = BAG_LVL_ID},
  },
  [605] = {
    {Image = BACK_SCRATCHER_TEX_ID},
    {Text = '擁有布的力量的無敵不求人'},
    {LevelId = BAG_LVL_ID},
  },
  [606] = {
    {NextCond = FlashlightOutOfPower, NextId = 608},
    {Image = flashlight_tex_id},
    {Text = '光線有點暗淡的手電筒'},
    {Text = '電力還能夠使用%d次', ScriptText = ScriptTextFlashlightUseCount},
    {LevelId = BAG_LVL_ID},
  },
  [607] = {
    {Image = MALLET_TEX_ID},
    {Text = '擁有石頭力量的神奇石頭棒'},
    {LevelId = BAG_LVL_ID},
  },
  [608] = {
    {Image = flashlight_tex_id},
    {Text = '沒有電力的手電筒'},
    {LevelId = BAG_LVL_ID},
  },
  [609] = {
    {Image = CANDY_TEX_ID},
    {Text = '好吃的棒棒糖'},
    {LevelId = BAG_LVL_ID},
  },
  [610] = {
    {Image = SCISSOR_TEX_ID},
    {Text = '豬妹妹的美勞剪刀'},
    {LevelId = BAG_LVL_ID},
  },
  [611] = {
    {Image = FROG_TEAR_TEX_ID},
    {Text = '小青蛙的眼淚'},
    {LevelId = BAG_LVL_ID},
  },
  [612] = {
    {Image = DRUM_STICK_TEX_ID},
    {Text = '搖滾阿凱的打鼓棒'},
    {LevelId = BAG_LVL_ID},
  },
  [613] = {
    {Image = SCISSOR_TEX_ID},
    {Text = '擁有剪刀力量的超級剪刀手'},
    {LevelId = BAG_LVL_ID},
  },
  [614] = {
    {Image = RPS_MEDAL_TEX_ID},
    {Text = '「猜拳高手證明書」'},
    {Text = '特頒發此證以證明'},
    {Text = '勇者小白戰勝拳頭星的猜拳大王'},
    {Text = '稱號為猜拳勇者'},
    {LevelId = BAG_LVL_ID},
  },
  [615] = {
    {Image = DIRTY_YELLOW_SUIT_OBJ_ID},
    {Text = '骯髒的黃色袍子'},
    {LevelId = BAG_LVL_ID},
  },
  [616] = {
    {Image = SUPER_SOAP_BOOK_TEX_ID},
    {Text = '「超強效洗衣精配方」'},
    {Text = '以下是製作超強效洗衣精的配方'},
    {Text = '1.三種不同顏色的老鼠尾巴'},
    {Text = '2.一滴青蛙的眼淚'},
    {Text = '3.一句秘密的魔法咒語'},
    {Text = '這樣就能產生一份超強效洗衣精'},
    {LevelId = BAG_LVL_ID},
  },
  [617] = {
    {Image = GREEN_MOUSE_TAIL_OBJ_ID},
    {Text = '綠色老鼠尾巴'},
    {LevelId = BAG_LVL_ID},
  },
  [618] = {
    {Image = RED_MOUSE_TAIL_OBJ_ID},
    {Text = '紅色老鼠尾巴'},
    {LevelId = BAG_LVL_ID},
  },
  [619] = {
    {Image = YELLOW_MOUSE_TAIL_OBJ_ID},
    {Text = '黃色老鼠尾巴'},
    {LevelId = BAG_LVL_ID},
  },
  [620] = {
    {Image = SUPER_SOAP_TEX_ID},
    {Text = '超強效洗衣精'},
    {LevelId = BAG_LVL_ID},
  },
  [621] = {
    {Image = CLEAN_YELLOW_SUIT_OBJ_ID},
    {Text = '乾淨的黃色袍子'},
    {LevelId = BAG_LVL_ID},
  },
  [622] = {
    {Image = ROPE_TEX_ID},
    {Text = '很長的繩索'},
    {LevelId = BAG_LVL_ID},
  },
  [623] = {
    {Image = UFO_POWER_TEX_ID},
    {Text = '外星人飛船能源'},
    {LevelId = BAG_LVL_ID},
  },
  [624] = {
    {Image = DIPSY_FEATHER_TEX_ID},
    {Text = '綠色的毛'},
    {LevelId = BAG_LVL_ID},
  },
  [625] = {
    {Image = LAALAA_FEATHER_TEX_ID},
    {Text = '黄色的毛'},
    {LevelId = BAG_LVL_ID},
  },
  [626] = {
    {Image = PO_FEATHER_TEX_ID},
    {Text = '紅色的毛'},
    {LevelId = BAG_LVL_ID},
  },
  [627] = {
    {Image = TINKY_WINKY_FEATHER_TEX_ID},
    {Text = '紫色的毛'},
    {LevelId = BAG_LVL_ID},
  },
  [628] = {
    {Image = SUPER_NANO_TOWEL_TEX_ID},
    {Text = 'S奈米擦布'},
    {LevelId = BAG_LVL_ID},
  },
  [629] = {
    {Image = FISH_TEX_ID},
    {Text = '可作成美味料理的魚'},
    {LevelId = BAG_LVL_ID},
  },
  [630] = {
    {Image = JEWEL_TEX_ID},
    {Text = '亮晶晶的寶石'},
    {LevelId = BAG_LVL_ID},
  },
  -- Church.
  [1000] = {
    {Image = pinnote_tex_id},
    {Text = '有事外出'},
    {LevelId = MAIN_MAP_LVL_ID},
  },
  [1150] = {
    {Image = priest_tex_id},
    {Text = '小兄弟辛苦你啦'},
    {Image = LETTER_TEX_ID},
    {Text = '從勇者山帶來這封信應該累了吧'},
    {Image = priest_tex_id},
    {Text = '請到後面讓我們為你馬殺雞'},
    {Text = string.format('友情價算你%d塊錢', CHURCH_RECV_LETTER_COST)},
    {Script = ScriptTransLetterToPriest},
    {Image = -1},
    {Text = ''},
    {FadeTo = {ONE_SECOND_TICK, COLOR_BLACK}},
    {Text = '「好舒服啊快要睡著了」'},
    {Text = 'ZZZ ZZZ ZZZ'},
    {Text = '救命啊'},
    {Text = '來人啊'},
    {Text = ''},
    {FadeTo = {ONE_SECOND_TICK, color_olive}},
    {Text = '救命啊'},
    {Text = '來人啊'},
    {Text = '「哇塞有人在喊救命了」'},
    {Text = '「該是輪到勇者我出場的時候了」'},
    {Image = dog_tex_id},
    {Text = '汪汪汪！汪汪汪！'},
    {Text = '「噓～安靜不要吵！」'},
    {Text = '「我現在要過去看看」'},
    {Text = '「小白二號不要怕！」'},
    {Text = '「你在後面掩護我」'},
    {Image = pinky_tex_id},
    {Text = '「豬小妹原來是妳啊！」'},
    {Text = '「豬小妹豬小妹妳怎麼了？」'},
    {Text = '救命啊有小強啊！'},
    {Image = dog_tex_id},
    {Text = '「來啊！進攻！」'},
    {LevelId = help_pinky_lvl_id},
  },
  [1151] = {
    {Image = pinky_tex_id},
    {Text = '謝謝你小白^^'},
    {Text = '「呵呵呵我是勇者小白！」'},
    {Text = '「我的任務是維護世界的和平！」'},
    {Text = ''},
    {Image = -1},
    {FadeTo = {ONE_SECOND_TICK, COLOR_BLACK}},
    {FadeTo = {ONE_SECOND_TICK, color_olive}},
    {Image = priest_tex_id},
    {Text = '小兄弟你醒啦'},
    {Text = '看你睡的那麼熟'},
    {Text = '應該休息夠了吧'},
    {Text = '以後累了歡迎再來抓龍哦'},
    {Text = '再馬一次就可以升級為VIP哦'},
    {Image = -1},
    {Text = '「原來是個夢」'},
    {LevelId = MAIN_MAP_LVL_ID},
  },
  [1152] = {
    {Image = priest_tex_id},
    {Text = '你累了嗎'},
    {Text = '請到後面讓我們為你馬殺雞'},
    {Text = string.format('特價算你%d塊錢', CHURCH_2ND_DREAM_COST)},
    {Script = Consume2ndDreamCost},
    {Image = -1},
    {Text = ''},
    {FadeTo = {ONE_SECOND_TICK, COLOR_BLACK}},
    {Text = '「好舒服啊快要睡著了」'},
    {Text = 'ZZZ ZZZ ZZZ'},
    {Text = ''},
    {FadeTo = {ONE_SECOND_TICK, color_olive}},
    {Image = grandpa_tex_id},
    {Text = '「爺爺爺爺」'},
    {Text = '「為什麼我們村叫作勇者村？」'},
    {Text = '小白啊總有一天你會了解的'},
    {Text = '「什麼時候呢？」'},
    {Text = '總有一天啊'},
    {Text = '先不談這個了'},
    {Text = '去把我的無敵不求人拿來'},
    {Text = '讓我抓抓癢先'},
    {Text = '「不求人就不求人」'},
    {Text = '「為什麼叫無敵不求人？」'},
    {Text = '這是我們家的傳家之寶'},
    {Text = '總有一天你會了解的'},
    {Text = '「......」'},
    {Text = '不多說了我要到教堂去'},
    {Text = '自己在外面玩要小心'},
    {Image = -1},
    {Text = ''},
    {Text = '「小白！小白！」'},
    {Text = '「奇怪？小白跑到那裡去了？」'},
    {Text = '「不管了我自己要出去玩了」'},
    {LevelId = interview_hero_village_lvl_id},
  },
  [1153] = {
    {Image = priest_tex_id},
    {Text = '你累了嗎抓個龍吧'},
    {Text = string.format('VIP特價%d塊錢哦', REST_COST)},
    {LevelId = MAIN_MAP_LVL_ID},
  },
  [1154] = {
    {Image = priest_tex_id},
    {Text = string.format('來抓個龍吧VIP只要%d塊錢哦', REST_COST)},
    {Script = ConsumeRestCost},
    {Image = -1},
    {Text = ''},
    {FadeTo = {ONE_SECOND_TICK, COLOR_BLACK}},
    {Text = '「好舒服啊快要睡著了」'},
    {Text = 'ZZZ ZZZ ZZZ'},
    {LevelId = HERO_VILLAGE_LVL_ID},
  },
  -- Main map temple site.
  [1200] = {
    {Image = pinnote_tex_id},
    {Text = '整備中'},
    {LevelId = MAIN_MAP_LVL_ID},
  },
  [1201] = {
    {Image = pinnote_tex_id},
    {Text = '募款蓋廟中'},
    {Text = '還需要$%d', ScriptText = ScriptTextCrowdFunding},
    {LevelId = MAIN_MAP_LVL_ID},
  },
  [1202] = {
    {Image = merchant_tex_id},
    {Text = '小兄弟您真行這麼快就募到錢了'},
    {Text = '蓋廟的事就交給我來辨吧'},
    {Script = ScriptBuildTemple},
    {LevelId = MAIN_MAP_LVL_ID},
  },
  [1203] = {
    {Image = GODZILLA_TEX_ID},
    {Text = '龍神太子財神廟建設中'},
    {LevelId = MAIN_MAP_LVL_ID},
  },
  [1204] = {
    {Image = GODZILLA_TEX_ID},
    {Text = '龍神太子財神廟建設完成'},
    {Text = '您成為龍神太子財神廟廟公'},
    {Script = ScriptTempleCreated},
    {LevelId = MAIN_MAP_LVL_ID},
  },
  [1205] = {
    {Image = GODZILLA_TEX_ID},
    {Text = '歡迎光臨龍神太子財神廟'},
    {LevelId = TEMPLE_LVL_ID},
  },
  -- Hero village church, grandpa.
  [1300] = {
    {Image = grandpa_tex_id},
    {Text = '外星人果然又來了'},
    {Text = '圖書館有本「勇者的故事」'},
    {Text = '你先去看看再來一下'},
    {Script = ScriptAddHeroHisBook},
    {LevelId = HERO_VILLAGE_CHURCH_LVL_ID},
  },
  [1301] = {
    {Image = grandpa_tex_id},
    {Text = '讀過祖先的記錄了吧'},
    {Text = '找到3把上古神兵打敗外星人吧'},
    {Text = ''},
    {Text = '「爺爺爺爺」'},
    {Text = '嗯嗯怎麼啦'},
    {Text = '「不求人不求人」'},
    {Text = '嗯嗯喔喔喔'},
    {Text = '沒錯！'},
    {Image = BACK_SCRATCHER_TEX_ID},
    {Text = '這就是擁有布的力量的無敵不求人'},
    {Text = '可以用來對抗石頭的力量'},
    {Text = '給你吧'},
    {Script = ScriptAddBackScratcher},
    {Image = grandpa_tex_id},
    {Text = '小白你現在是新一代的勇者了'},
    {Text = '「呵呵呵我是勇者小白！」'},
    {Text = '「我的任務是維護世界的和平！」'},
    {Text = '去把另外2把神兵找出來'},
    {Text = '打敗外星人拯救這個世界吧'},
    {LevelId = HERO_VILLAGE_CHURCH_LVL_ID},
  },
  [1302] = {
    {Image = grandpa_tex_id},
    {Text = '找到3把上古神兵打敗外星人吧'},
    {LevelId = HERO_VILLAGE_CHURCH_LVL_ID},
  },
  [1303] = {
    {Image = grandpa_tex_id},
    {Text = '張媽媽家擁有石頭的力量'},
    {Text = '去張媽媽家看看吧'},
    {LevelId = HERO_VILLAGE_CHURCH_LVL_ID},
  },
  [1304] = {
    {Image = grandpa_tex_id},
    {Text = '小白這是今天給你的零用錢'},
    {Text = '拿去買你喜歡的東西吧'},
    {Script = ScriptGiveAllowance},
    {Text = '「謝謝爺爺」'},
    {LevelId = HERO_VILLAGE_CHURCH_LVL_ID},
  },
  [1305] = {
    {Image = grandpa_tex_id},
    {Text = '圖書館裡有本書你可以看看'},
    {Text = '它記載著開啟洞穴之門的方法'},
    {Script = ScriptAddCaveDoorBook},
    {Text = '「好的謝謝爺爺」'},
    {LevelId = HERO_VILLAGE_CHURCH_LVL_ID},
  },
  [1306] = {
    {Image = grandpa_tex_id},
    {Text = '豬妹妹家擁有剪刀的力量'},
    {Text = '去豬妹妹家看看吧'},
    {LevelId = HERO_VILLAGE_CHURCH_LVL_ID},
  },
  [1307] = {
    {Image = grandpa_tex_id},
    {Text = '地底國的小矮人需要幫忙'},
    {LevelId = HERO_VILLAGE_CHURCH_LVL_ID},
  },
  [1308] = {
    {Image = grandpa_tex_id},
    {Text = '我記得開啟洞穴之門的書的旁邊'},
    {Text = '就有一本書是關於迷宮的'},
    {Text = '你可以看看'},
    {Script = ScriptAddCaveMazeBook},
    {LevelId = HERO_VILLAGE_CHURCH_LVL_ID},
  },
  [1309] = {
    {Image = grandpa_tex_id},
    {Text = '這捆繩索給你帶著吧'},
    {Image = ROPE_TEX_ID},
    {Text = '到地底國去應該用的到'},
    {Script = ScriptAddRope},
    {LevelId = HERO_VILLAGE_CHURCH_LVL_ID},
  },
  [1310] = {
    {Image = grandpa_tex_id},
    {Text = '外星人的科技很發達'},
    {Text = '應該有辨法修理眼鏡'},
    {LevelId = HERO_VILLAGE_CHURCH_LVL_ID},
  },
  [1311] = {
    {Image = grandpa_tex_id},
    {Text = '說到外星人的飛船能源'},
    {Text = '印象中有本書裡面有提到過'},
    {Text = '你到圖書館去看看吧'},
    {Script = ScriptAddUfoPowerBook},
    {LevelId = HERO_VILLAGE_CHURCH_LVL_ID},
  },
  [1312] = {
    {Image = grandpa_tex_id},
    {Text = '如果港口有船可以出海的話'},
    {Text = '就可以到更廣闊的世界冒險了'},
    {LevelId = HERO_VILLAGE_CHURCH_LVL_ID},
  },
  [1313] = {
    {Image = grandpa_tex_id},
    {Text = '勇敢的到寛廣的世界去冒險吧'},
    {Text = '無畏的到遼闊的宇宙去冒險吧'},
    {LevelId = HERO_VILLAGE_CHURCH_LVL_ID},
  },
  -- Hero village church, books.
  [1350] = {
    {Image = HERO_HIS_BOOK_TEX_ID},
    {Text = '「勇者的故事」'},
    {Text = '很久很久以前'},
    {Text = '邪惡的外星人來到勇者村'},
    {Text = '想要征服這個世界'},
    {Text = '三個勇者拿著傳說的神兵'},
    {Text = '勇敢的去挑戰魔王'},
    {Text = '三把傳說中的神兵分別是'},
    {Text = '擁有剪刀力量的超級剪刀手'},
    {Text = '擁有石頭力量的神奇石頭棒'},
    {Text = '擁有布的力量的無敵不求人'},
    {Text = '最後三位勇者打敗了魔王'},
    {Text = '拯救了這個世界'},
    {Text = '從此大家過著快快樂樂的日子'},
    {LevelId = BAG_LVL_ID},
  },
  [1351] = {
    {Image = CAVE_DOOR_BOOK_TEX_ID},
    {Text = '「開啟洞穴之門的方法」'},
    {Text = '勇者們打敗魔王後'},
    {Text = '將石頭的力量封印在洞穴'},
    {Text = '以下是開啟密門的方法'},
    {ScriptText = GetOpenCaveDoorCode},
    {LevelId = BAG_LVL_ID},
  },
  [1352] = {
    {Image = POWER_SCISSOR_BOOK_TEX_ID},
    {Text = '「超級剪刀手之書」'},
    {Text = '要想獲得超級剪刀手'},
    {Text = '首先準備一把美勞剪刀'},
    {Text = '還要一根打鼓棒'},
    {Text = '以及一滴青蛙眼淚'},
    {Text = '最後大聲說出魔法咒語'},
    {Text = '「超級剪刀手出來吧」'},
    {Text = '就能合成超級剪刀手了'},
    {LevelId = BAG_LVL_ID},
  },
  [1353] = {
    {Image = SLAP_MOUSE_BOOK_TEX_ID},
    {Text = '「超級老鼠拍打器 by 小明」'},
    {Text = '1.按下紅色按鈕 拍打器跑出來'},
    {Text = '2.按下綠色按鈕 球跑出來'},
    {Text = '3.按下黃色按鈕 起士跑出來'},
    {Text = '4.老鼠跑來吃起士'},
    {Text = '5.老鼠踩到球跌倒'},
    {Text = '6.拍打器打下來打死老鼠'},
    {LevelId = BAG_LVL_ID},
  },
  [1354] = {
    {Image = CAVE_MAZE_BOOK_TEX_ID},
    {Text = '「地底王國迷宮之書」'},
    {Text = '要找到迷宮出口進入地底王國'},
    {Text = '需按照底下步驟走迷宮'},
    {Text = '右上上右上上右上'},
    {Text = '最後看到一口井'},
    {Text = '井底就是地底王國了'},
    {Text = '如果迷路了的話'},
    {Text = '只要一直往南走就能找到出口'},
    {Text = '附帶一提'},
    {Text = '在迷宮的北邊深處有一面鏡子'},
    {Text = '是傳說的真理之鏡'},
    {Text = '能讓你照見平常看不見的秘密'},
    {LevelId = BAG_LVL_ID},
  },
  [1355] = {
    {Image = SHAVE_BOOK_TEX_ID},
    {Text = '「修鬍子的技巧 by 豬爸爸」'},
    {Text = '首先要一條毛巾'},
    {Text = '先把你的臉洗乾淨'},
    {Text = '再來需要一瓶修鬍子水'},
    {Text = '塗在鬍子上修起來會更滑順'},
    {Text = '然後需要一把修鬍子專用的剪刀'},
    {Text = '細心的修成你需要的樣子'},
    {Text = '還需要一面鏡子'},
    {Text = '看看結果滿不滿意'},
    {Text = '不滿意的話再重復上面步驟'},
    {Text = '直到滿意為止'},
    {Text = '最後再用洗面皂和毛巾'},
    {Text = '把臉洗乾淨就全部完成了'},
    {LevelId = BAG_LVL_ID},
  },
  [1356] = {
    {Image = UFO_POWER_BOOK_TEX_ID},
    {Text = '「飛船能源之書」'},
    {Text = '很久很久以前'},
    {Text = '三個勇者拿著傳說的神兵'},
    {Text = '以猜拳和外星人一決勝負後'},
    {Text = '勇者和外星人成為好朋友後'},
    {Text = '外星人回到拳頭星'},
    {Text = '離開時留下多餘的飛船能源'},
    {Text = '儲藏在地底迷宮的真理之鏡中'},
    {LevelId = BAG_LVL_ID},
  },
  -- UFO coming.
  [1400] = {
    {FadeTo = {ONE_SECOND_TICK, COLOR_BLACK}},
    {Image = ufo_obj_id},
    {Text = '哇哈哈哇哈哈！我又來啦！'},
    {Text = '我是拳頭星的猜拳大王'},
    {Text = '我要征服勇者村'},
    {Text = '然後再征服這個世界'},
    {Text = '快把勇者交出來吧'},
    {Text = '否則就嘿嘿嘿嘿嘿嘿！'},
    {LevelId = HERO_VILLAGE_LVL_ID},
  },
  -- Hero village, Zhang mama home.
  [1500] = {
    {Image = zhang_mama_tex_id},
    {Text = '每天都要洗好多衣服啊'},
    {LevelId = HERO_VILLAGE_LVL_ID},
  },
  [1501] = {
    {NextCond = FlashlightOutOfPower, NextId = 1502},
    {Image = zhang_mama_tex_id},
    {Text = '我們家的傳家之寶神奇石頭棒'},
    {Text = '封印在洞穴內被祖先保護著'},
    {Text = '要通過考驗才能拿到'},
    {LevelId = HERO_VILLAGE_LVL_ID},
  },
  [1502] = {
    {Image = zhang_mama_tex_id},
    {Text = '每天都要洗好多衣服啊'},
    {Text = '小白你來的正好'},
    {Text = '請你幫我曬一下衣服'},
    {Text = '曬好了我再給你一些零用錢'},
    {LevelId = clothes_drying_lvl_id},
  },
  [1503] = {
    {Image = zhang_mama_tex_id},
    {Text = '小白謝謝你的幫忙'},
    {Text = '這是給你的零用錢'},
    {Text = '拿去買你喜歡的東西吧'},
    {Script = ScriptGiveAllowance},
    {Text = '「謝謝張媽媽」'},
    {LevelId = HERO_VILLAGE_LVL_ID},
  },
  [1504] = {
    {NextCond = FlashlightOutOfPower, NextId = 1502},
    {Image = zhang_mama_tex_id},
    {Text = '己經打門封印洞穴的門了嗎'},
    {Text = '小白你真是了不起'},
    {Text = '你只要對著空的寶箱說出咒語'},
    {Text = '「神奇石頭棒出來吧」'},
    {Text = '擁有石頭力量的寶物就會出現了'},
    {Script = ScriptGetMalletCode},
    {LevelId = HERO_VILLAGE_LVL_ID},
  },
  [1505] = {
    {Image = zhang_mama_tex_id},
    {Text = '你這件袍子太髒了我沒辨法洗'},
    {Text = '準備好超強效洗衣精後再來找我'},
    {Text = '請你先幫我曬一下衣服吧'},
    {Text = '曬好了我再給你一些零用錢'},
    {LevelId = clothes_drying_lvl_id},
  },
  [1506] = {
    {Image = zhang_mama_tex_id},
    {Text = '超強效洗衣精己準備好的話'},
    {Text = '我們就一起來把這件袍子洗乾淨吧'},
    {Image = -1},
    {Text = ''},
    {FadeTo = {ONE_SECOND_TICK, COLOR_BLACK}},
    {Text = '嘿咻嘿咻洗刷刷洗刷刷'},
    {Text = '洗刷刷洗刷刷嘿咻嘿咻'},
    {FadeTo = {ONE_SECOND_TICK, color_olive}},
    {Image = CLEAN_YELLOW_SUIT_OBJ_ID},
    {Text = '終於把這件袍子洗乾淨了'},
    {Script = ScriptCleanYellowSuit},
    {Image = zhang_mama_tex_id},
    {Text = '「謝謝張媽媽的幫忙」'},
    {LevelId = HERO_VILLAGE_LVL_ID},
  },
  -- Hero village, Shop.
  [1600] = {
    {Image = pinnote_tex_id},
    {Text = '今日公休'},
    {LevelId = HERO_VILLAGE_LVL_ID},
  },
  [1601] = {
    {Image = merchant_tex_id},
    {Text = string.format('高級手電筒只賣%d塊錢', FLASHLIGHT_COST)},
    {Text = '要買要快哦'},
    {LevelId = HERO_VILLAGE_LVL_ID},
  },
  [1602] = {
    {Image = merchant_tex_id},
    {Text = '小白你運氣真好'},
    {Text = '這是最後一個高級手電筒了'},
    {Image = flashlight_tex_id},
    {Text = string.format('收你%d塊錢謝謝惠顧', FLASHLIGHT_COST)},
    {Script = ScriptBuyFlashlight},
    {LevelId = HERO_VILLAGE_LVL_ID},
  },
  [1603] = {
    {NextCond = IsFlashlightBuyable, NextId = 1604},
    {Image = merchant_tex_id},
    {Text = string.format('手電筒充電一次只要%d塊錢', FLASHLIGHT_COST)},
    {LevelId = HERO_VILLAGE_LVL_ID},
  },
  [1604] = {
    {Image = merchant_tex_id},
    {Text = string.format('收你%d塊錢謝謝惠顧', FLASHLIGHT_COST)},
    {Script = ScriptChargeFlashlight},
    {Text = '手電筒充滿電了'},
    {LevelId = HERO_VILLAGE_LVL_ID},
  },
  [1605] = {
    {NextCond = IsFlashlightBuyable, NextId = 1604},
    {Image = merchant_tex_id},
    {Text = string.format('好吃的棒棒糖只賣%d塊錢', CANDY_COST)},
    {Text = '要買要快哦'},
    {LevelId = HERO_VILLAGE_LVL_ID},
  },
  [1606] = {
    {Image = merchant_tex_id},
    {Text = string.format('收你%d塊錢謝謝惠顧', CANDY_COST)},
    {Image = CANDY_TEX_ID},
    {Text = '這是給您的好吃的棒棒糖'},
    {Script = ScriptBuyCandy},
    {LevelId = HERO_VILLAGE_LVL_ID},
  },
  [1607] = {
    {Image = merchant_tex_id},
    {Text = '我正在收集青蛙眼淚製作藥劑'},
    {Text = '請你把青蛙眼淚賣給我吧'},
    {Image = FROG_TEAR_TEX_ID},
    {Script = ScriptSellFrogTear},
    {Text = '一手交錢一手交貨'},
    {Image = merchant_tex_id},
    {Text = '謝謝你小白'},
    {LevelId = HERO_VILLAGE_LVL_ID},
  },
  [1608] = {
    {NextCond = FlashlightOutOfPower, NextId = 1603},
    {NextCond = HasFrogTearToSell, NextId = 1607},
    {NextCond = HasMouseTailToSell, NextId = 1611},
    {NextCond = HasSuperNanoTowel, NextId = 1612},
    {NextCond = HasFeatherToSell, NextId = 1613},
    {Image = pinnote_tex_id},
    {Text = '今日公休'},
    {LevelId = HERO_VILLAGE_LVL_ID},
  },
  [1609] = {
    {Image = merchant_tex_id},
    {Text = '抱歉我沒有賣超強效洗衣精'},
    {Text = '不過圖書館有本說明書'},
    {Text = '記載了製作超強效洗衣精的配方'},
    {Text = '如果你收集齊製作配方的話'},
    {Text = '我可以免費幫你製作哦'},
    {Script = ScriptAddSuperSoapBook},
    {LevelId = HERO_VILLAGE_LVL_ID},
  },
  [1610] = {
    {Image = merchant_tex_id},
    {Text = '讓我們來檢查看看'},
    {Text = '超強效洗衣精的配方是否全部到齊'},
    {Image = RED_MOUSE_TAIL_OBJ_ID},
    {Text = '紅色老鼠尾巴'},
    {Image = GREEN_MOUSE_TAIL_OBJ_ID},
    {Text = '綠色老鼠尾巴'},
    {Image = YELLOW_MOUSE_TAIL_OBJ_ID},
    {Text = '黃色老鼠尾巴'},
    {Image = FROG_TEAR_TEX_ID},
    {Text = '青蛙的眼淚'},
    {Image = merchant_tex_id},
    {Text = '太好了全部齊全了'},
    {Text = '再來加上我的秘密的咒語'},
    {Text = '就能製作出一份超強效洗衣精'},
    {Text = '「阿布卡阿布卡」'},
    {Image = SUPER_SOAP_TEX_ID},
    {Text = '獲得一份超強效洗衣精'},
    {Script = ScriptAddSuperSoap},
    {Text = '小白如果以後你有其它老鼠尾巴'},
    {Text = '記得賣給我哦'},
    {LevelId = HERO_VILLAGE_LVL_ID},
  },
  [1611] = {
    {Image = merchant_tex_id},
    {Text = '我正在收集老鼠尾巴'},
    {Text = '要用來製作出超強效洗衣精'},
    {Text = '請你賣給我吧'},
    {Script = ScriptSellMouseTail},
    {Text = '一手交錢一手交貨'},
    {Text = '謝謝你小白'},
    {LevelId = HERO_VILLAGE_LVL_ID},
  },
  [1612] = {
    {Image = merchant_tex_id},
    {Text = '哇這是稀有的S奈米擦布'},
    {Text = '請你賣給我吧'},
    {Image = SUPER_NANO_TOWEL_TEX_ID},
    {Text = '一手交錢一手交貨'},
    {Script = ScriptSellSuperNanoTowel},
    {Image = merchant_tex_id},
    {Text = '謝謝你小白'},
    {LevelId = HERO_VILLAGE_LVL_ID},
  },
  [1613] = {
    {Image = merchant_tex_id},
    {Text = '哇這是稀有的外星人的毛'},
    {Text = '請你賣給我吧'},
    {Script = ScriptSellFeather},
    {Text = '一手交錢一手交貨'},
    {Text = '謝謝你小白'},
    {LevelId = HERO_VILLAGE_LVL_ID},
  },
  -- Hero village, Pinky home.
  [1700] = {
    {Image = pinky_tex_id},
    {Text = '小白要跟我一起玩哦'},
    {LevelId = HERO_VILLAGE_LVL_ID},
  },
  [1701] = {
    {Image = pinky_tex_id},
    {Text = '咔嚓咔嚓剪剪剪'},
    {Text = '哈哈哈勞作真好玩'},
    {Script = ScriptBuyCandyLoop},
    {LevelId = HERO_VILLAGE_LVL_ID},
  },
  [1702] = {
    {Image = pinky_tex_id},
    {Text = '咔嚓咔嚓剪剪剪'},
    {Text = '哈哈哈勞作真好玩'},
    {Text = '小白跟我一起作勞作'},
    {Image = CANDY_TEX_ID},
    {Text = '哇哇是好吃的棒棒糖ㄟ'},
    {Text = '可以給我吃嗎'},
    {Text = '謝謝你小白你真好^^'},
    {Image = SCISSOR_TEX_ID},
    {Text = '這個剪刀給你'},
    {Script = ScriptExchangeCandyScissor},
    {Image = pinky_tex_id},
    {Text = '小白要跟我一起玩哦'},
    {LevelId = HERO_VILLAGE_LVL_ID},
  },
  [1703] = {
    {Text = '哦哦糟糕'},
    {Text = '這把美勞剪刀好像對付不了外星人'},
    {Text = '要再想想其它辨法才行'},
    {Script = ScriptPowerupScissorLoop},
    {LevelId = ALIEN_PATH_LVL_ID},
  },
  [1704] = {
    {Image = pinky_papa_tex_id},
    {Text = '呵呵呵小白好久不見'},
    {Text = '你知道魔法咒語嗎？'},
    {Text = '要讓美勞剪刀變成超級剪刀手'},
    {Text = '你得去圖書館找找看'},
    {Script = ScriptAddPowerScissorBook},
    {LevelId = HERO_VILLAGE_LVL_ID},
  },
  [1705] = {
    {Image = pinky_papa_tex_id},
    {Text = '呵呵呵小白好久不見'},
    {Text = '看來你很努力的把東西都集齊了'},
    {Text = '讓我們一起來升級超級剪刀手吧'},
    {Image = SCISSOR_TEX_ID},
    {Text = '首先要一把美勞剪刀'},
    {Image = DRUM_STICK_TEX_ID},
    {Text = '還要一根打鼓棒'},
    {Image = FROG_TEAR_TEX_ID},
    {Text = '以及一滴青蛙眼淚'},
    {Image = -1},
    {Text = '最後讓我們一起大聲說出魔法咒語'},
    {Text = '「超級剪刀手出來吧」'},
    {Image = SCISSOR_TEX_ID},
    {Script = ScriptPowerupScissor},
    {Text = '獲得擁有剪刀力量的超級剪刀手'},
    {LevelId = HERO_VILLAGE_LVL_ID},
  },
  [1706] = {
    {Image = pinky_tex_id},
    {Text = '小白要跟我一起玩哦'},
    {Image = JOHN_TEX_ID},
    {Text = '哇啊啊啊救命啊有小強啊！'},
    {Text = '小白快來救我'},
    {LevelId = help_pinky_lvl_id},
  },
  [1707] = {
    {Image = pinky_tex_id},
    {Text = '謝謝你小白^^'},
    {Text = '「呵呵呵我是勇者小白！」'},
    {Text = '「我的任務是維護世界的和平！」'},
    {LevelId = HERO_VILLAGE_LVL_ID},
  },
  [1708] = {
    {Image = pinky_papa_tex_id},
    {Text = '呵呵呵小白好久不見'},
    {Text = '修鬍子的事情找我就對了'},
    {Text = '讓我來教教你怎麼作'},
    {Text = '首先要一條毛巾'},
    {Text = '先把你的臉洗乾淨'},
    {Text = '再來需要一瓶修鬍子水'},
    {Text = '塗在鬍子上修起來會更滑順'},
    {Text = '然後需要一把修鬍子專用的剪刀'},
    {Text = '細心的修成你需要的樣子'},
    {Text = '還需要一面鏡子'},
    {Text = '看看結果滿不滿意'},
    {Text = '不滿意的話再重復上面步驟'},
    {Text = '直到滿意為止'},
    {Text = '最後再用洗面皂和毛巾'},
    {Text = '把臉洗乾淨就全部完成了'},
    {Image = SHAVE_BOOK_TEX_ID},
    {Text = '如果你覺得很複雜的話'},
    {Text = '圖書館有本書是我的心得之作'},
    {Text = '你可以研究研究看看'},
    {Script = ScriptAddShaveBook},
    {Image = SCISSOR_TEX_ID},
    {Text = '不過如果有超級剪刀手的話'},
    {Text = '修鬍子就很簡單了'},
    {Text = '只要拿著它對著要修鬍子的人'},
    {Text = '說出魔法咒語'},
    {Text = '「阿布卡BB」'},
    {Text = '就樣就可以修好鬍子了'},
    {Text = '「...」'},
    {Text = '「我知道了謝謝豬爸爸」'},
    {LevelId = HERO_VILLAGE_LVL_ID},
  },
  [1709] = {
    {Image = pinky_papa_tex_id},
    {Text = '呵呵呵小白好久不見'},
    {Text = '我在動物園打工'},
    {Text = '賺點零用錢給豬小妹買零食'},
    {LevelId = ZOO_LVL_ID},
  },
  -- Hero village, hero home.
  [1800] = {
    {Text = '「爺爺知道很多事情」'},
    {Text = '「先去教堂找爺爺再回來休息」'},
    {LevelId = HERO_VILLAGE_LVL_ID},
  },
  [1801] = {
    {Text = '「維護世界的和平也是挺累的」'},
    {Text = '「讓我睡一下下吧」'},
    {Text = ''},
    {FadeTo = {ONE_SECOND_TICK, COLOR_BLACK}},
    {FadeTo = {ONE_SECOND_TICK, color_olive}},
    {Image = priest_tex_id},
    {Text = '小兄弟你醒啦'},
    {Text = '恭喜你成為我們的VIP'},
    {Text = '以後累了歡迎再來抓龍哦'},
    {Image = -1},
    {Text = '「原來是個夢」'},
    {LevelId = MAIN_MAP_LVL_ID},
  },
  [1802] = {
    {Text = '「維護世界的和平也是挺累的」'},
    {Text = '「讓我睡一下下吧」'},
    {Text = ''},
    {FadeTo = {ONE_SECOND_TICK, COLOR_BLACK}},
    {FadeTo = {ONE_SECOND_TICK, color_olive}},
    {Text = '「原來是個夢」'},
    {LevelId = MAIN_MAP_LVL_ID},
  },
  -- Country, Kai home.
  [1900] = {
    {Image = kai_tex_id},
    {Text = '我是搖滾阿凱'},
    {Text = '又又又一起來搖滾吧'},
    {LevelId = COUNTRY_LVL_ID},
  },
  [1901] = {
    {Image = kai_tex_id},
    {Text = '小青蛙又偷跑出去玩了'},
    {LevelId = COUNTRY_LVL_ID},
  },
  [1902] = {
    {Image = kai_tex_id},
    {Text = '最近我買了超級老鼠拍打器'},
    {Text = '如果你能幫忙我抓老鼠'},
    {Text = '我就把打鼓棒送給你'},
    {Text = '你可以先到教堂圖書館去'},
    {Text = '研究研究一下使用說明書再來'},
    {Script = ScriptAddSlapMouseBook},
    {LevelId = COUNTRY_LVL_ID},
  },
  [1903] = {
    {Image = kai_tex_id},
    {Text = '請用超級老鼠拍打器幫我抓老鼠'},
    {LevelId = slap_mouse_lvl_id},
  },
  [1904] = {
    {Image = kai_tex_id},
    {Text = '真是太謝謝你了'},
    {Text = '幫我抓那麼多老鼠'},
    {Image = DRUM_STICK_TEX_ID},
    {Text = '照約定我的打鼓棒送給你'},
    {Script = ScriptAddDrumStick},
    {LevelId = COUNTRY_LVL_ID},
  },
  [1905] = {
    {Image = kai_tex_id},
    {Text = '真是太謝謝你了'},
    {Text = '幫我抓那麼多老鼠'},
    {Text = '這是一點打工錢'},
    {Text = '有空再麻煩你來幫我抓老鼠哦'},
    {Script = ScriptGiveAllowance},
    {LevelId = COUNTRY_LVL_ID},
  },
  [1906] = {
    {Image = kai_tex_id},
    {Text = '真是太謝謝你了'},
    {Text = '幫我抓那麼多老鼠'},
    {Text = '送你一個%s色老鼠尾巴', ScriptText = ScriptTextAddMouseTail},
    {Text = '有空再麻煩你來幫我抓老鼠哦'},
    {LevelId = COUNTRY_LVL_ID},
  },
  -- Country, pond,
  [2000] = {
    {Image = frog_tex_id},
    {Text = '呱呱呱'},
    {LevelId = COUNTRY_LVL_ID},
  },
  [2001] = {
    {Image = frog_tex_id},
    {Text = '呱呱呱'},
    {Text = '「哦原來是偷跑的小青蛙」'},
    {Text = '「我們一起來玩躲貓貓吧」'},
    {LevelId = seek_frog_lvl_id},
  },
  [2002] = {
    {Image = frog_tex_id},
    {Text = '為什麼你都找的到我'},
    {Text = '呱呱呱嗚嗚嗚'},
    {Image = FROG_TEAR_TEX_ID},
    {Text = '得到了青蛙的眼淚'},
    {Script = ScriptAddFrogTear},
    {LevelId = COUNTRY_LVL_ID},
  },
  -- Cave field, cave.
  [2100] = {
    {FadeTo = {ONE_SECOND_TICK, COLOR_BLACK}},
    {Text = '黑漆漆的山洞什麼都看不見'},
    {Script = ScriptEnterCave},
    {LevelId = CAVE_FIELD_LVL_ID},
  },
  [2101] = {
    {FadeTo = {ONE_SECOND_TICK, COLOR_BLACK}},
    {Text = '黑漆漆的山洞什麼都看不見'},
    {Script = ScriptEnterCave},
    {Text = '慢慢的往前模索前進'},
    {Text = '好像摸到一扇門'},
    {Text = '如果有手電筒就好了'},
    {LevelId = CAVE_FIELD_LVL_ID},
  },
  [2102] = {
    {NextCond = FlashlightOutOfPower, NextId = 2107},
    {FadeTo = {ONE_SECOND_TICK, COLOR_BLACK}},
    {Text = '黑漆漆的山洞什麼都看不見'},
    {Text = '拿出手電筒打開開關'},
    {FadeTo = {ONE_SECOND_TICK, color_olive}},
    {Script = ScriptEnterCave},
    {Script = ScriptUseFlashlight},
    {Text = '光線有點暗淡不過可以看見了'},
    {Image = cave_door_tex_id},
    {Text = '走到盡頭發現一道門'},
    {Text = '需要密碼才能打開門'},
    {LevelId = CAVE_DOOR_LVL_ID},
  },
  [2103] = {
    {NextCond = FlashlightOutOfPower, NextId = 2107},
    {Script = ScriptEnterCave},
    {Script = ScriptUseFlashlight},
    {Text = '光線有點暗淡'},
    {Image = cave_door_tex_id},
    {Text = '走到盡頭發現一道門'},
    {Text = '需要密碼才能打開門'},
    {LevelId = CAVE_DOOR_LVL_ID},
  },
  [2104] = {
    {NextCond = HasGetMalletCode, NextId = 2105},
    {NextCond = HasMallet, NextId = 2106},
    {Text = '密碼輸入正確門開了'},
    {Image = chest_tex_id},
    {Text = '發現一個寶箱'},
    {Text = '打開寶箱裡面是空的！'},
    {LevelId = CAVE_FIELD_LVL_ID},
  },
  [2105] = {
    {Text = '密碼輸入正確門開了'},
    {Image = chest_tex_id},
    {Text = '對著空寶箱說出通關咒語'},
    {Text = '「神奇石頭棒出來吧」'},
    {Image = MALLET_TEX_ID},
    {Text = '得到擁有石頭力量的神奇石頭棒'},
    {Text = '可以用來對抗剪刀的力量'},
    {Script = ScriptAddMellet},
    {LevelId = CAVE_FIELD_LVL_ID},
  },
  [2106] = {
    {Text = '密碼輸入正確門開了'},
    {Image = chest_tex_id},
    {Text = '己經得到寶箱裡的神奇石頭棒了'},
    {LevelId = CAVE_FIELD_LVL_ID},
  },
  [2107] = {
    {FadeTo = {ONE_SECOND_TICK, COLOR_BLACK}},
    {Text = '黑漆漆的山洞什麼都看不見'},
    {Text = '手電筒沒電了無法使用'},
    {LevelId = CAVE_FIELD_LVL_ID},
  },
  [2108] = {
    {Text = '密碼輸入正確門開了'},
    {Image = chest_tex_id},
    {Text = '打開空寶箱'},
    {Text = '仔細一看箱子底部還有個門'},
    {Text = '但是不知道怎麼打開'},
    {LevelId = CAVE_FIELD_LVL_ID},
  },
  [2109] = {
    {Image = dwarf_tex_id},
    {Text = '勇者小白尼好'},
    {Text = '偶是來自地底王國的小地瓜'},
    {Text = '偶們的長老們邀請尼'},
    {Text = '竭誠歡迎尼到偶們的王國來玩玩'},
    {Text = '偶們的長老們另外有事請尼幫忙'},
    {Text = '洞口密碼門和寶箱密門偶都拆掉了'},
    {Text = '那麼偶們就地底王國見囉'},
    {Script = ScriptAddCaveMazeBookFlag},
    {LevelId = CAVE_FIELD_LVL_ID},
  },
  [2110] = {
    {NextCond = FlashlightOutOfPower, NextId = 2107},
    {Script = ScriptUseFlashlight},
    {Text = '光線有點暗淡'},
    {Image = chest_tex_id},
    {Text = '走到洞穴盡頭打開空寶箱'},
    {Text = '進入地底王國'},
    {Text = ''},
    {Image = -1},
    {FadeTo = {ONE_SECOND_TICK, COLOR_GRAY}},
    {LevelId = cave_maze_lvl_id},
  },
  [2111] = {
    {BgColor = COLOR_GRAY},
    {Image = well_tex_id},
    {Text = '這口井好像很深的樣子'},
    {Text = '不知道該怎麼下去才好'},
    {Script = ScriptSetNeedRopeFlag},
    {LevelId = cave_maze_lvl_id},
  },
  [2112] = {
    {BgColor = COLOR_GRAY},
    {Image = well_tex_id},
    {Text = '終於可以進入地底王國了'},
    {LevelId = UNDER_WORLD_ENTRANCE_LVL_ID},
  },
  [2113] = {
    {BgColor = COLOR_GRAY},
    {Image = mirror_tex_id},
    {Text = '這是一面有點破損的鏡子'},
    {Text = '走近前去照照鏡子'},
    {Image = dog_tex_id},
    {Text = '「小白！」'},
    {Image = mirror_tex_id},
    {Text = '「奇怪是我眼睛花了嗎？」'},
    {Text = '「這面鏡子好奇怪」'},
    {LevelId = cave_maze_lvl_id},
  },
  [2114] = {
    {BgColor = COLOR_GRAY},
    {Image = mirror_tex_id},
    {Text = '這是一面有點破損的鏡子'},
    {Text = '走近前去仔細檢查'},
    {Text = '發現底下有個開關可以打開鏡子'},
    {Image = UFO_POWER_TEX_ID},
    {Text = '在鏡子後面發現飛船能源'},
    {Script = ScriptAddUfoPower},
    {LevelId = cave_maze_lvl_id},
  },
  -- Alien area, ufo.
  [2200] = {
    {Image = UFO_TEX_ID},
    {Text = '勇者小白你終於來了'},
    {Text = '我們就以猜拳來一決勝敗吧'},
    {LevelId = alien_boss_lvl_id},
  },
  [2201] = {
    {NextCond = HasRpsMedal, NextId = 2202},
    {Image = UFO_TEX_ID},
    {Text = '我是拳頭星的猜拳大王ㄟ'},
    {Text = '想不到你用猜拳戰勝了我'},
    {Text = '果然人外有人天外有天'},
    {Text = '我要頒發一個證書給你'},
    {Text = '證明你是戰勝猜拳大王的猜拳勇者'},
    {Image = RPS_MEDAL_TEX_ID},
    {Script = ScriptAddRpsMedal},
    {Text = '我還要繼續加油努力'},
    {Text = '有空要再來找我猜拳哦'},
    {LevelId = ALIEN_AREA_LVL_ID},
  },
  [2202] = {
    {Image = UFO_TEX_ID},
    {Text = '我是拳頭星的猜拳大王ㄟ'},
    {Text = '怎麼又輸給你這個猜拳勇者了'},
    {Text = '我還要繼續加油努力'},
    {Text = '有空要再來找我猜拳哦'},
    {LevelId = ALIEN_AREA_LVL_ID},
  },
  [2203] = {
    {Image = UFO_TEX_ID},
    {Text = '以拳頭星的科技來看'},
    {Text = '你說的眼鏡應該只是磨損嚴重'},
    {Text = '只要有S奈米擦布就很容易修復'},
    {Text = '不過我現在沒有S奈米擦布'},
    {Text = '必須回到拳頭星才能取得'},
    {Text = '而且我的船因為動力不足'},
    {Text = '也無法飛回到拳頭星'},
    {Text = '如果能夠得到能源補充的話'},
    {Text = '我就能用飛船帶你到拳頭星'},
    {Text = '這樣就能取得S奈米擦布'},
    {Script = ScriptFindUfoPower},
    {Text = '哎呀不說了我們還是來猜拳吧'},
    {LevelId = alien_boss_lvl_id},
  },
  [2204] = {
    {Image = UFO_TEX_ID},
    {Text = '得到能源補充的話'},
    {Text = '我就能用飛船帶你到拳頭星'},
    {Text = '這樣就能取得S奈米擦布修復眼鏡'},
    {Text = '哎呀不說了我們還是來猜拳吧'},
    {LevelId = alien_boss_lvl_id},
  },
  [2205] = {
    {Image = UFO_TEX_ID},
    {Text = '勇者小白你真是太厲害啦'},
    {Text = '你是怎麼找到飛船能源補充的？'},
    {Text = '不管了現在可以帶你到拳頭星了'},
    {Text = '立刻出發吧'},
    {Script = ScriptConsumeUfoPower},
    {LevelId = astroid_lvl_id},
  },
  [2206] = {
    {Image = UFO_TEX_ID},
    {Text = '勇者小白你來啦'},
    {MenuText = {'比賽猜拳', '去拳頭星'}, MenuNextId = {2207, 2208}},
  },
  [2207] = {
    {LevelId = alien_boss_lvl_id},
  },
  [2208] = {
    {LevelId = astroid_lvl_id},
  },
  [2209] = {
    {Image = UFO_TEX_ID},
    {Text = '勇者小白你想回勇者村了嗎？'},
    {MenuText = {'立刻出發', '再等等'}, MenuNextId = {2210, 2211}},
  },
  [2210] = {
    {LevelId = ALIEN_AREA_LVL_ID},
  },
  [2211] = {
    {LevelId = JANKEN_PLANET_LVL_ID},
  },
  -- Under world entry, well.
  [2300] = {
    {BgColor = COLOR_GRAY},
    {Image = well_tex_id},
    {Text = '按照原路回到地面上吧'},
    {LevelId = CAVE_FIELD_LVL_ID},
  },
  -- Under world entry, dwarf potato.
  [2400] = {
    {BgColor = COLOR_GRAY},
    {Image = dwarf_tex_id},
    {Text = '勇者小白尼好'},
    {Text = '偶是地底王國的小地瓜'},
    {Text = '歡迎尼到偶們的王國'},
    {LevelId = UNDER_WORLD_ENTRANCE_LVL_ID},
  },
  [2401] = {
    {NextCond = HasJewel, NextId = 2403},
    {BgColor = COLOR_GRAY},
    {Image = dwarf_tex_id},
    {Text = '勇者小白尼好'},
    {Text = '偶是地底王國的小地瓜'},
    {Text = '偶想要再給尼一個小小的測驗'},
    {LevelId = pair_game_lvl_id},
  },
  [2402] = {
    {BgColor = COLOR_GRAY},
    {Image = dwarf_tex_id},
    {Text = '勇者小白尼好'},
    {Text = '讓偶來幫尼把蝙蝠洞打開'},
    {Image = -1},
    {FadeTo = {ONE_SECOND_TICK, COLOR_BLACK}},
    {Text = '敲敲打打敲敲打打'},
    {Text = '打打敲敲打打敲敲'},
    {FadeTo = {ONE_SECOND_TICK, COLOR_GRAY}},
    {Image = dwarf_tex_id},
    {Text = '偶己經把蝙蝠洞打開了'},
    {Script = ScriptOpenBatCave},
    {LevelId = UNDER_WORLD_ENTRANCE_LVL_ID},
  },
  [2403] = {
    {BgColor = COLOR_GRAY},
    {Image = dwarf_tex_id},
    {Text = '勇者小白尼好'},
    {Text = '請尼把亮晶晶的寶石賣給偶'},
    {Text = '偶最喜歡亮晶晶的寶石'},
    {Image = JEWEL_TEX_ID},
    {Text = '十分感謝尼'},
    {Script = ScriptSellJewel},
    {Image = dwarf_tex_id},
    {Text = '還有寶石的話請全都賣偶'},
    {LevelId = UNDER_WORLD_ENTRANCE_LVL_ID},
  },
  -- Under world entry, to main map.
  [2500] = {
    {BgColor = COLOR_GRAY},
    {Image = dwarf_tex_id},
    {Text = '勇者小白尼好'},
    {Text = '進入偶們的王國之前'},
    {Text = '偶想要給尼一個小小的測驗'},
    {LevelId = pair_game_lvl_id},
  },
  [2501] = {
    {BgColor = COLOR_GRAY},
    {Image = dwarf_tex_id},
    {Text = '恭喜通過這個小小的測驗'},
    {NextCond = IsPassPotatoTest, NextId = 2502},
    {Text = '請進入偶們的王國'},
    {Script = ScriptPassPotatoTest},
    {Image = -1},
    {Text = ''},
    {FadeTo = {ONE_SECOND_TICK, COLOR_BLACK}},
    {FadeTo = {ONE_SECOND_TICK, COLOR_GRAY}},
    {Image = elder_glass_tex_id},
    {Text = '尼好偶是眼鏡長老'},
    {Image = elder_yellow_tex_id},
    {Text = '尼好偶是黃袍長老'},
    {Image = elder_white_tex_id},
    {Text = '尼好偶是白鬍子長老'},
    {Image = elder_glass_tex_id},
    {Text = '歡迎尼來到地底王國'},
    {Image = elder_yellow_tex_id},
    {Text = '歡迎尼來到地底王國'},
    {Image = elder_white_tex_id},
    {Text = '歡迎尼來到地底王國'},
    {LevelId = UNDERWORLD_MAIN_LVL_ID},
  },
  [2502] = {
    {BgColor = COLOR_GRAY},
    {Image = dwarf_tex_id},
    {Text = '隨時歡迎尼再來挑戰哦'},
    {LevelId = UNDER_WORLD_ENTRANCE_LVL_ID},
  },
  -- Under world main, elder glass.
  [2600] = {
    {BgColor = COLOR_GRAY},
    {Image = elder_glass_tex_id},
    {Text = '尼好偶是眼鏡長老'},
    {Text = '偶的眼镜最近老是看不清楚'},
    {Text = '應該需要修理一下了'},
    {Text = '尼能幫忙嗎？'},
    {MenuText = {'沒問題', '我沒空'}, MenuNextId = {2601, 2602}},
  },
  [2601] = {
    {BgColor = COLOR_GRAY},
    {Image = elder_glass_tex_id},
    {Text = '「沒問題交給我來處理」'},
    {Text = '「我先研究看看怎麼處理」'},
    {Script = ScriptHelpElderGlass},
    {LevelId = UNDERWORLD_MAIN_LVL_ID},
  },
  [2602] = {
    {BgColor = COLOR_GRAY},
    {Image = elder_glass_tex_id},
    {Text = '「抱歉我沒空」'},
    {Text = '「請你再找別人幫你」'},
    {LevelId = UNDERWORLD_MAIN_LVL_ID},
  },
  [2603] = {
    {BgColor = COLOR_GRAY},
    {Image = elder_glass_tex_id},
    {Text = '請問偶的眼镜怎麼辨？'},
    {LevelId = UNDERWORLD_MAIN_LVL_ID},
  },
  [2604] = {
    {BgColor = COLOR_GRAY},
    {Image = elder_glass_tex_id},
    {Text = '「抱歉讓您久等了」'},
    {Text = '「我己經得到S奈米擦布」'},
    {Text = '「請容我為您服務」'},
    {Image = SUPER_NANO_TOWEL_TEX_ID},
    {Image = -1},
    {Text = ''},
    {FadeTo = {ONE_SECOND_TICK, COLOR_BLACK}},
    {Text = '「我擦擦擦我擦擦擦」'},
    {FadeTo = {ONE_SECOND_TICK, COLOR_GRAY}},
    {Image = elder_glass_tex_id},
    {Text = '哇哇哇哇'},
    {Text = '偶的眼鏡變得好清晰啊！'},
    {Text = '謝謝尼勇者小白'},
    {Script = ScriptHelpElderGlassDone},
    {LevelId = UNDERWORLD_MAIN_LVL_ID},
  },
  [2605] = {
    {NextCond = HasSuperNanoTowel, NextId = 2606},
    {BgColor = COLOR_GRAY},
    {Image = elder_glass_tex_id},
    {Text = '謝謝尼勇者小白'},
    {LevelId = UNDERWORLD_MAIN_LVL_ID},
  },
  [2606] = {
    {BgColor = COLOR_GRAY},
    {Image = elder_glass_tex_id},
    {Text = '最近偶的眼鏡有點看不清楚'},
    {Image = SUPER_NANO_TOWEL_TEX_ID},
    {Text = '請尼把S奈米擦布賣給我'},
    {Script = ScriptSellSuperNanoTowel},
    {Image = elder_glass_tex_id},
    {Text = '謝謝尼勇者小白'},
    {LevelId = UNDERWORLD_MAIN_LVL_ID},
  },
  -- Under world main, elder yellow.
  [2610] = {
    {BgColor = COLOR_GRAY},
    {Image = elder_yellow_tex_id},
    {Text = '尼好偶是黃袍長老'},
    {Text = '偶的袍子己經又臭又髒'},
    {Text = '應該需要洗一洗了'},
    {Text = '尼能幫忙嗎？'},
    {MenuText = {'OKOK', 'NONO'}, MenuNextId = {2611, 2612}},
  },
  [2611] = {
    {BgColor = COLOR_GRAY},
    {Image = elder_yellow_tex_id},
    {Text = '「OKOK我來幫你洗洗」'},
    {Text = '「請將你的袍子交給我吧」'},
    {Script = ScriptHelpElderYellow},
    {LevelId = UNDERWORLD_MAIN_LVL_ID},
  },
  [2612] = {
    {BgColor = COLOR_GRAY},
    {Image = elder_yellow_tex_id},
    {Text = '「NONO好臭我不敢洗」'},
    {Text = '「請你找別人來幫忙吧」'},
    {LevelId = UNDERWORLD_MAIN_LVL_ID},
  },
  [2613] = {
    {BgColor = COLOR_GRAY},
    {Image = elder_yellow_tex_id},
    {Text = '請問偶的袍子洗好了嗎？'},
    {LevelId = UNDERWORLD_MAIN_LVL_ID},
  },
  [2614] = {
    {BgColor = COLOR_GRAY},
    {Image = elder_yellow_tex_id},
    {Text = '「抱歉讓您久等了」'},
    {Image = CLEAN_YELLOW_SUIT_OBJ_ID},
    {Text = '「我己經將您的袍子洗乾淨了」'},
    {Image = elder_yellow_tex_id},
    {Text = '哇哇哇哇'},
    {Text = '偶的袍子變得好乾淨啊！'},
    {Text = '謝謝尼勇者小白'},
    {Script = ScriptHelpElderYellowDone},
    {LevelId = UNDERWORLD_MAIN_LVL_ID},
  },
  [2615] = {
    {BgColor = COLOR_GRAY},
    {Image = elder_yellow_tex_id},
    {Text = '謝謝尼勇者小白'},
    {LevelId = UNDERWORLD_MAIN_LVL_ID},
  },
  -- Under world main, elder white.
  [2620] = {
    {BgColor = COLOR_GRAY},
    {Image = elder_white_tex_id},
    {Text = '尼好偶是白鬍子長老'},
    {Text = '偶的鬍子長得太長太亂了'},
    {Text = '應該需要修剪了'},
    {Text = '尼能幫忙嗎？'},
    {MenuText = {'好啊', '對不起'}, MenuNextId = {2621, 2622}},
  },
  [2621] = {
    {BgColor = COLOR_GRAY},
    {Image = elder_white_tex_id},
    {Text = '「好啊不過我不會修鬍子」'},
    {Text = '「等我學會了再來幫你哦」'},
    {Script = ScriptHelpElderWhite},
    {LevelId = UNDERWORLD_MAIN_LVL_ID},
  },
  [2622] = {
    {BgColor = COLOR_GRAY},
    {Image = elder_white_tex_id},
    {Text = '「對不起我不會修鬍子」'},
    {Text = '「請你再找找別人幫忙吧」'},
    {LevelId = UNDERWORLD_MAIN_LVL_ID},
  },
  [2623] = {
    {BgColor = COLOR_GRAY},
    {Image = elder_white_tex_id},
    {Text = '偶還在等尼幫偶修鬍子哦'},
    {LevelId = UNDERWORLD_MAIN_LVL_ID},
  },
  [2624] = {
    {BgColor = COLOR_GRAY},
    {Image = elder_white_tex_id},
    {Text = '「抱歉讓您久等了」'},
    {Text = '「我己經學會怎麼修鬍子了」'},
    {Text = '「請容我為您服務」'},
    {Image = SCISSOR_TEX_ID},
    {Text = '「阿布卡BB」'},
    {Image = -1},
    {Text = ''},
    {FadeTo = {ONE_SECOND_TICK, COLOR_BLACK}},
    {FadeTo = {ONE_SECOND_TICK, COLOR_GRAY}},
    {Image = elder_white_tex_id},
    {Text = '哇哇哇哇'},
    {Text = '偶的鬍子變得好滑順乾淨啊！'},
    {Text = '謝謝尼勇者小白'},
    {LevelId = UNDERWORLD_MAIN_LVL_ID},
  },
  [2625] = {
    {BgColor = COLOR_GRAY},
    {Image = elder_white_tex_id},
    {Text = '謝謝尼勇者小白'},
    {LevelId = UNDERWORLD_MAIN_LVL_ID},
  },
  -- Trash field, old lady.
  [2700] = {
    {BgColor = COLOR_GRAY},
    {Image = old_lady_tex_id},
    {Text = '勇者小白尼好'},
    {Text = '我是貓洞貓媽媽'},
    {Text = '這裡實在是太髒亂了'},
    {Text = '可以請尼幫忙打掃一下嗎？'},
    {LevelId = pick_trash_lvl_id},
  },
  [2701] = {
    {BgColor = COLOR_GRAY},
    {Image = old_lady_tex_id},
    {Text = '勇者小白真是謝謝尼'},
    {Text = '幫忙打掃的好乾淨啊'},
    {Text = '這是給尼的一點零用錢'},
    {Script = ScriptGiveAllowance},
    {Text = '改天偶再跟貓咪們好好招待尼'},
    {LevelId = TRASH_FIELD_LVL_ID},
  },
  [2702] = {
    {BgColor = COLOR_GRAY},
    {Image = old_lady_tex_id},
    {Text = '勇者小白尼好'},
    {Text = '偶的貓咪孩子們最近魚不夠吃了'},
    {Text = '如果尼有多的魚賣給偶的話'},
    {Text = '偶們都會很開心很感謝尼的'},
    {LevelId = TRASH_FIELD_LVL_ID},
  },
  [2703] = {
    {NextCond = HasFish, NextId = 2704},
    {NextId = 2700},
  },
  [2704] = {
    {BgColor = COLOR_GRAY},
    {Image = old_lady_tex_id},
    {Text = '勇者小白尼好'},
    {Image = FISH_TEX_ID},
    {Text = '這條魚看起來真是新鮮美味'},
    {Text = '請尼把魚賣給偶們'},
    {Script = ScriptSellFish},
    {Image = old_lady_tex_id},
    {Text = '勇者小白真是謝謝尼'},
    {LevelId = TRASH_FIELD_LVL_ID},
  },
  -- Trash field, magic mama.
  [2800] = {
    {BgColor = COLOR_GRAY},
    {Image = magic_mama_tex_id},
    {Text = '我是魔法婆婆'},
    {NextCond = CanPlayLottery, NextId = 2801},
    {Text = '等你有錢再來吧'},
    {LevelId = TRASH_FIELD_LVL_ID},
  },
  [2801] = {
    {BgColor = COLOR_GRAY},
    {Image = magic_mama_tex_id},
    {Text = '來試試你的手氣吧'},
    {Script = ScriptPlayLottery},
    {LevelId = lottery_lvl_id},
  },
  [2802] = {
    {BgColor = COLOR_GRAY},
    {Image = magic_mama_tex_id},
    {Text = '謝謝惠顧歡迎再來'},
    {LevelId = TRASH_FIELD_LVL_ID},
  },
  -- Janken planet, Dipsy.
  [2900] = {
    {Image = DIPSY_TEX_ID},
    {Text = '你好'},
    {LevelId = JANKEN_PLANET_LVL_ID},
  },
  [2901] = {
    {Image = DIPSY_TEX_ID},
    {Text = '我們來玩個拼圖遊戲吧'},
    {LevelId = puzzle_lvl_id},
  },
  [2902] = {
    {Image = DIPSY_TEX_ID},
    {Text = '你好棒棒哦'},
    {Text = '送你一根綠色的毛'},
    {Script = ScriptAddDipsyFeather},
    {Text = '再見'},
    {LevelId = JANKEN_PLANET_LVL_ID},
  },
  -- Janken planet, Po.
  [3000] = {
    {Image = po_tex_id},
    {Text = '你好'},
    {LevelId = JANKEN_PLANET_LVL_ID},
  },
  [3001] = {
    {Image = po_tex_id},
    {Text = '試試看你的記憶力好不好'},
    {LevelId = memory_lvl_id},
  },
  [3002] = {
    {Image = po_tex_id},
    {Text = '你好棒棒哦'},
    {Text = '送你一根紅色的毛'},
    {Script = ScriptAddPoFeather},
    {Text = '再見'},
    {LevelId = JANKEN_PLANET_LVL_ID},
  },
  -- Janken planet, Laalaa.
  [3100] = {
    {Image = laalaa_tex_id},
    {Text = '你好'},
    {LevelId = JANKEN_PLANET_LVL_ID},
  },
  [3101] = {
    {Image = laalaa_tex_id},
    {Text = '找找看我在那裡'},
    {LevelId = shadow_lvl_id},
  },
  [3102] = {
    {Image = laalaa_tex_id},
    {Text = '你好棒棒哦'},
    {Text = '送你一根黄色的毛'},
    {Script = ScriptAddLaaLaaFeather},
    {Text = '再見'},
    {LevelId = JANKEN_PLANET_LVL_ID},
  },
  -- Janken planet, Tinky Winky.
  [3200] = {
    {Image = tinkywinky_tex_id},
    {Text = '你好'},
    {LevelId = JANKEN_PLANET_LVL_ID},
  },
  [3201] = {
    {Image = tinkywinky_tex_id},
    {Text = '一起來玩彩虹遊戲吧'},
    {LevelId = rainbow_lvl_id},
  },
  [3202] = {
    {Image = tinkywinky_tex_id},
    {Text = '你好棒棒哦'},
    {Text = '送你一根紫色的毛'},
    {Script = ScriptAddTinkyWinkyFeather},
    {Text = '再見'},
    {LevelId = JANKEN_PLANET_LVL_ID},
  },
  -- Janken lib, bebe.
  [3300] = {
    {Image = bebe_tex_id},
    {Text = '你好我是比比博士'},
    {Text = '我可以幫忙製作S奈米擦布'},
    {Text = '首先需要四根天線寶寶的毛'},
    {Text = '材料收集好後再來找我吧'},
    {Script = ScriptFindTeletubbies},
    {LevelId = INSIDE_JANKEN_LIB_LVL_ID},
  },
  [3301] = {
    {NextCond = HasSuperNanoTowel, NextId = 3302},
    {NextCond = HasFourFeathers, NextId = 3303},
    {Image = bebe_tex_id},
    {Text = '你好我是比比博士'},
    {LevelId = INSIDE_JANKEN_LIB_LVL_ID},
  },
  [3302] = {
    {Image = bebe_tex_id},
    {Text = '我是比比博士'},
    {Text = '你己經有一條S奈米擦布了'},
    {Text = '下次有需要再來找我吧'},
    {LevelId = INSIDE_JANKEN_LIB_LVL_ID},
  },
  [3303] = {
    {Image = bebe_tex_id},
    {Text = '太好了'},
    {Text = '四根天線寶寶的毛全部齊全了'},
    {Text = '我現在幫你製作S奈米擦布'},
    {Text = '請稍等'},
    {Image = -1},
    {FadeTo = {ONE_SECOND_TICK, COLOR_BLACK}},
    {FadeTo = {ONE_SECOND_TICK, color_olive}},
    {Image = SUPER_NANO_TOWEL_TEX_ID},
    {Text = 'S奈米擦布製作完成'},
    {Script = ScriptMakeSuperNanoTowel},
    {Image = bebe_tex_id},
    {Text = '下次有需要再來找我哦'},
    {LevelId = INSIDE_JANKEN_LIB_LVL_ID},
  },
  -- Janken lib, computer.
  [3350] = {
    {Image = bebe_tex_id},
    {Text = '你好我是比比博士'},
    {Image = computer_tex_id},
    {Text = '我正在研發一台虛擬實境遊戲機'},
    {Text = '要創造一個奇幻的冒險世界'},
    {Image = JEWEL_TEX_ID},
    {Text = '我還需要一顆寶石'},
    {Text = '因為這是電腦的核心元件'},
    {Image = bebe_tex_id},
    {Text = '如果你能幫我收集來的話'},
    {Text = '就讓你永久免費使用'},
    {LevelId = INSIDE_JANKEN_LIB_LVL_ID},
  },
  [3351] = {
    {Image = bebe_tex_id},
    {Text = '太好了這就是我需要的寶石'},
    {Image = JEWEL_TEX_ID},
    {Text = '我現在就用它來啟動電腦'},
    {Script = ScriptTakeJewel},
    {Text = '請稍等'},
    {Image = -1},
    {FadeTo = {ONE_SECOND_TICK, COLOR_BLACK}},
    {FadeTo = {ONE_SECOND_TICK, color_olive}},
    {Image = bebe_tex_id},
    {Text = '虛擬實境遊戲機製作完成'},
    {NextId = 3352},
  },
  [3352] = {
    {Image = computer_tex_id},
    {Text = '歡迎使用虛擬實境遊戲機'},
    {LevelId = COMPUTER_LVL_ID},
  },
  -- Janken observatory.
  [3380] = {
    {Image = pinnote_tex_id},
    {Text = '歡迎光臨拳頭星天文台'},
    {LevelId = JANKEN_OBSERVATORY_LVL_ID},
  },
  -- Bat cave field, bat cave.
  [3400] = {
    {FadeTo = {ONE_SECOND_TICK, COLOR_BLACK}},
    {Text = '洞口被大石塊封住了'},
    {LevelId = BAT_CAVE_FIELD_LVL_ID},
  },
  [3401] = {
    {FadeTo = {ONE_SECOND_TICK, COLOR_BLACK}},
    {Text = '洞口被大石塊封住了'},
    {Text = '好像有一個小洞'},
    {Text = '洞裡面黑漆漆的什麼都看不見'},
    {Text = '有大量蝙蝠飛行的聲音'},
    {Script = ScriptBatCaveBlocked},
    {LevelId = BAT_CAVE_FIELD_LVL_ID},
  },
  [3402] = {
    {FadeTo = {ONE_SECOND_TICK, COLOR_BLACK}},
    {Text = '不愧是蝙蝠洞好多蝙蝠'},
    {Text = '讓我來練習一下打蝙蝠'},
    {LevelId = bat_cave_lvl_id},
  },
  [3403] = {
    {BgColor = COLOR_BLACK},
    {Text = '「嘿嘿我又進步了」'},
    {Text = '繼續加油挑戰下一關'},
    {LevelId = snake_cave_lvl_id},
  },
  [3404] = {
    {BgColor = COLOR_BLACK},
    {Text = '「嘿嘿我又進步了」'},
    {Text = '繼續加油挑戰下一關'},
    {LevelId = mouse_cave_lvl_id},
  },
  [3405] = {
    {BgColor = COLOR_BLACK},
    {Text = '「嘿嘿我又進步了」'},
    {Text = '繼續加油挑戰下一關'},
    {LevelId = jewel_cave_lvl_id},
  },
  [3406] = {
    {NextCond = HasJewel, NextId = 3407},
    {BgColor = COLOR_BLACK},
    {Text = '「嘿嘿我又進步了」'},
    {Text = '走到蝙蝠洞底部'},
    {Image = JEWEL_TEX_ID},
    {Text = '獲得一顆寶石'},
    {Script = ScriptAddJewel},
    {LevelId = BAT_CAVE_FIELD_LVL_ID},
  },
  [3407] = {
    {BgColor = COLOR_BLACK},
    {Text = '「嘿嘿我又進步了」'},
    {Text = '還要繼續努力不斷進步'},
    {LevelId = BAT_CAVE_FIELD_LVL_ID},
  },
  -- Dock, dock.
  [3500] = {
    {Image = dock_tex_id},
    {Text = '有船的話就能夠出海了'},
    {LevelId = DOCK_LVL_ID},
  },
  -- Dock, fishman.
  [3550] = {
    {Image = fishman_tex_id},
    {Text = '大海無限寛廣擁有一切可能'},
    {LevelId = DOCK_LVL_ID},
  },
  [3551] = {
    {Image = fishman_tex_id},
    {Text = '小白啊我跟你說'},
    {Text = '我己經老了不能再出海捕魚了'},
    {Text = string.format('如果你有%d塊錢的話', SHIP_COST)},
    {Text = '我就把我的船賣給你'},
    {Text = '這樣你就可以出海去冒險了'},
    {LevelId = DOCK_LVL_ID},
  },
  [3552] = {
    {Image = fishman_tex_id},
    {Text = string.format('收您%d塊錢我的船就賣給你了', SHIP_COST)},
    {Script = ScriptBuyShip},
    {Image = SHIP_TEX_ID},
    {Text = '船就在港口可以隨時使用'},
    {Image = fishman_tex_id},
    {Text = '小白啊謝謝你'},
    {LevelId = DOCK_LVL_ID},
  },
  [3553] = {
    {NextCond = HasFish, NextId = 3554},
    {Image = fishman_tex_id},
    {Text = '有沒有新鮮的魚賣給我啊'},
    {LevelId = DOCK_LVL_ID},
  },
  [3554] = {
    {Image = fishman_tex_id},
    {Text = '小白啊這條魚看起來很新鮮'},
    {Image = FISH_TEX_ID},
    {Text = '請你把魚賣給我吧'},
    {Script = ScriptSellFishToFishman},
    {Image = fishman_tex_id},
    {Text = '小白啊謝謝你'},
    {LevelId = DOCK_LVL_ID},
  },
  -- Fish field, fish.
  [3600] = {
    {Image = FISH_TEX_ID},
    {Text = '來釣魚囉'},
    {LevelId = fishing_lvl_id},
  },
  [3601] = {
    {Image = FISH_TEX_ID},
    {Text = '釣到美味的魚囉'},
    {Script = ScriptAddFish},
    {LevelId = FISH_FIELD_LVL_ID},
  },
  -- Dq, castle.
  [3700] = {
    {Image = castle_obj_id},
    {Text = '小白你終於來啦'},
    {Text = '我己經等你好久了'},
    {Text = '請你幫我這個老人一個忙'},
    {Text = '把在外修練的王子和公主找回來'},
    {Text = '我要讓他們一起接掌這個國家'},
    {Text = '而我呢就能安心的退位去種田了'},
    {MenuText = {'遵命', '抱歉'}, MenuNextId = {3701, 3702}},
    {LevelId = DQ_LVL_ID},
  },
  [3701] = {
    {Image = castle_obj_id},
    {Text = '很好很好'},
    {Text = '我就知道你勇於接受挑戰'},
    {Text = '那麼就麻煩你了'},
    {NextId = 3703},
  },
  [3702] = {
    {Image = castle_obj_id},
    {Text = '小白我相信你一定可以的'},
    {Text = '請你一定要加油'},
    {Text = '接受這個挑戰'},
    {NextId = 3703},
  },
  [3703] = {
    {Image = castle_obj_id},
    {Text = '等你回來我將授予你'},
    {Text = '「勇者小白」的稱號'},
    {Script = ScriptAddKingPermission},
    {NextId = 3704},
  },
  [3704] = {
    {Image = castle_obj_id},
    {Text = '我知道王子在北邊的雪之國修練'},
    {Text = '但北方的紅白兩國正在戰爭'},
    {Text = '目前還無法通行'},
    {Text = '你得先幫忙解決兩國爭端'},
    {LevelId = DQ_LVL_ID},
  },
  [3705] = {
    {Image = pinnote_tex_id},
    {Text = '無國王許可禁止通行'},
    {LevelId = DQ_LVL_ID},
  },
  -- Dq, red castle.
  [3750] = {
    {Image = red_castle_obj_id},
    {Text = '紅之國是最強的'},
    {LevelId = NORTH_NATION_LVL_ID},
  },
  -- Dq, white castle.
  [3780] = {
    {Image = white_castle_obj_id},
    {Text = '白之國是無敵的'},
    {LevelId = NORTH_NATION_LVL_ID},
  },
  -- Dq, red castle training.
  [3790] = {
    {Image = pinnote_tex_id},
    {Text = '紅之國訓練場'},
    {LevelId = red_training_lvl_id},
  },
  [3791] = {
    {Text = '你真是一個神射手'},
    {Text = '請繼續加油！'},
    {LevelId = NORTH_NATION_LVL_ID},
  },
  -- Dq, white castle training.
  [3795] = {
    {Image = pinnote_tex_id},
    {Text = '白之國訓練場'},
    {LevelId = white_training_lvl_id},
  },
  [3796] = {
    {Text = '你真是一個勇敢的騎士'},
    {Text = '請繼續加油！'},
    {LevelId = NORTH_NATION_LVL_ID},
  },
  -- Island field, island.
  [3800] = {
    {Image = pinnote_tex_id},
    {Text = '歡迎來到我們這一家之島'},
    {LevelId = ISLAND_LVL_ID},
  },
  -- Island, my papa.
  [3900] = {
    {Image = my_papa_tex_id},
    {Text = '我是爸爸'},
    {LevelId = ISLAND_LVL_ID},
  },
  -- Island, my mama.
  [4000] = {
    {Image = my_mama_tex_id},
    {Text = '我是媽媽'},
    {Text = '哎唷討厭ㄋㄟ'},
    {Text = '我的拖鞋又跑到哪裡去了啦'},
    {Text = '快幫我找一下'},
    {LevelId = find_slippers_lvl_id},
  },
  [4001] = {
    {Image = my_mama_tex_id},
    {Text = '謝謝你喔'},
    {LevelId = ISLAND_LVL_ID},
  },
  -- Island, my guan.
  [4100] = {
    {Image = my_guan_tex_id},
    {Text = '我是小光'},
    {Text = '啦啦啦我最愛唱歌跳舞了'},
    {Text = '跟我一起玩吧'},
    {LevelId = music_game_lvl_id},
  },
  [4101] = {
    {Image = my_guan_tex_id},
    {Text = '真的好開心哦'},
    {Text = '要再我跟一起玩哦'},
    {LevelId = ISLAND_LVL_ID},
  },
  -- Island, my ming.
  [4200] = {
    {Image = my_ming_tex_id},
    {Text = '我是小明'},
    {Text = '爸爸說從小就要有時間觀念'},
    {Text = '我們一起來練習看看'},
    {LevelId = set_clock_lvl_id},
  },
  [4201] = {
    {Image = my_ming_tex_id},
    {Text = '太好了'},
    {Text = '要繼續練習哦'},
    {LevelId = ISLAND_LVL_ID},
  },
  -- Zoo island, to zoo island.
  [4300] = {
    {Image = pinnote_tex_id},
    {Text = '歡迎光臨動物園之島'},
    {LevelId = ZOO_FIELD_LVL_ID},
  },
  -- Zoo field, worm cave.
  [4400] = {
    {FadeTo = {ONE_SECOND_TICK, COLOR_BLACK}},
    {Text = '蚯蚓洞'},
    {LevelId = ZOO_FIELD_LVL_ID},
  },
}
